# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b55eb955747424e18467a9314059f59e299de30f2e5cfa2406e234526c1484c31b4c70becfea371b18644a05b1c0dd41aa278fa68273b9221f9030c475cf47d6

test:
  secret_key_base: f0638c73965fa26aa131d1024ecd45173e6365caaad5404420de247aa1da9c3ebc01ad42ddb9087b8dc465cfa03e66a113fdeffe9fe178bc5c5ed062c4e86213

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
